### ISSUE TITLE
Is there a case where the bins role needs to be resigned?

### ISSUE THREAD

**Issue by trishankatdatadog** [secure-systems-lab/peps#25]
Is there a case where the bins role (offline key) needs to be resigned?

**Comment by trishankatdatadog** [comment]
@lukpueh were you worried about this is the context of the Key Compromise Analysis? I'm trying to figure out where to write about this...

**Comment by lukpueh** [comment]
Apologies, @trishankatdatadog, I only just now saw that question. 

I asked my question originally referring to the "Revoking Trust in Projects and Versions" section, because it used to talk about removing delegations and re-signing bins (see https://github.com/secure-systems-lab/peps/commit/7426e7b48195380d71f9f6a1e84be20e49dd9473). @JustinCappos and I have fixed this in https://github.com/secure-systems-lab/peps/pull/31 in the meanwhile. So we can close here.
